include: package:very_good_analysis/analysis_options.5.0.0.yaml

linter:
  rules:
    public_member_api_docs: false
    comment_references: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    depend_on_referenced_packages: false
    no_leading_underscores_for_local_identifiers: false
